# Generated by Django 5.1.6 on 2025-02-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="分类名称")),
                ("order", models.IntegerField(verbose_name="分类排序")),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "category",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("types", models.IntegerField(verbose_name="类型")),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("language", models.CharField(max_length=255, verbose_name="语言")),
                ("poster", models.CharField(max_length=255, verbose_name="海报")),
                ("description", models.TextField(verbose_name="描述")),
                ("ratings", models.FloatField(verbose_name="评分")),
                ("douban_id", models.IntegerField(verbose_name="豆瓣ID")),
                ("actors", models.CharField(max_length=255, verbose_name="演员")),
                ("directors", models.CharField(max_length=255, verbose_name="导演")),
                ("country", models.CharField(max_length=255, verbose_name="国家")),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "db_table": "movie",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "无效"), (1, "有效")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.movie",
                        verbose_name="电影ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "db_table": "banner",
            },
        ),
        migrations.CreateModel(
            name="Urls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=255, verbose_name="链接")),
                ("url_type", models.IntegerField(verbose_name="链接类型")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "无效"), (1, "有效")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.movie",
                        verbose_name="电影ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "链接",
                "verbose_name_plural": "链接",
                "db_table": "urls",
                "ordering": ["-create_time"],
            },
        ),
    ]
