# Generated by Django 4.2.17 on 2025-02-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='banner',
            name='poster',
            field=models.CharField(default='', max_length=255, verbose_name='海报'),
        ),
    ]
