# Generated by Django 4.2.17 on 2025-02-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_banner_order_banner_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '类型',
                'db_table': 'types',
            },
        ),
    ]
