# Generated by Django 4.2.17 on 2025-02-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.types', verbose_name='类型'),
        ),
    ]
