# Generated by Django 4.2.17 on 2025-02-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_banner_create_time_alter_banner_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='url_type',
        ),
    ]
